const express = require('express');
const mongoose = require('mongoose');
const cors = require('cors');
const jwt = require('jsonwebtoken');
require('dotenv').config();

const app = express();
const PORT = process.env.PORT || 3000;

// Middleware
app.use(cors());
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(express.static('.'));

// JWT Secret
const JWT_SECRET = process.env.JWT_SECRET || 'lotato-pro-super-secret-key-2024';

// Connexion MongoDB
const MONGODB_URI = process.env.MONGODB_URI || 'mongodb://localhost:27017/lotato';

console.log('🔧 Initialisation de la connexion MongoDB...');

const mongooseOptions = {
  useNewUrlParser: true,
  useUnifiedTopology: true,
  serverSelectionTimeoutMS: 10000,
  socketTimeoutMS: 45000,
  maxPoolSize: 10,
  retryWrites: true,
  w: 'majority'
};

const connectWithRetry = async () => {
  try {
    await mongoose.connect(MONGODB_URI, mongooseOptions);
    console.log('✅ Connecté à MongoDB avec succès');
    console.log(`📊 Base de données: ${mongoose.connection.db.databaseName}`);
  } catch (err) {
    console.error('❌ Échec de connexion à MongoDB:', err.message);
    console.log('🔄 Nouvelle tentative dans 5 secondes...');
    setTimeout(connectWithRetry, 5000);
  }
};

mongoose.connection.on('connected', () => {
  console.log('🔗 Mongoose connecté à MongoDB');
});

mongoose.connection.on('error', (err) => {
  console.error('❌ Erreur de connexion Mongoose:', err.message);
});

mongoose.connection.on('disconnected', () => {
  console.log('🔌 Mongoose déconnecté de MongoDB');
});

connectWithRetry();

// === SCHÉMAS EXISTANTS ===
const ticketSchema = new mongoose.Schema({
  ticketId: { type: String, required: true, unique: true },
  agentId: { type: String, required: true },
  agentName: { type: String, required: true },
  drawId: { type: String, required: true },
  drawName: { type: String, required: true },
  bets: [{
    game: String,
    number: String,
    cleanNumber: String,
    amount: Number,
    isAutoGenerated: Boolean,
    specialType: String,
    gain: { type: Number, default: 0 }
  }],
  total: { type: Number, required: true },
  checked: { type: Boolean, default: false },
  date: { type: Date, default: Date.now }
});

const winnerSchema = new mongoose.Schema({
  ticketId: { type: String, required: true },
  agentId: { type: String, required: true },
  agentName: { type: String, required: true },
  drawId: { type: String, required: true },
  drawName: { type: String, required: true },
  gameType: { type: String, required: true },
  winningNumber: { type: String, required: true },
  winningAmount: { type: Number, required: true },
  customerName: { type: String, default: '' },
  paid: { type: Boolean, default: false },
  date: { type: Date, default: Date.now }
});

const agentSchema = new mongoose.Schema({
  agentId: { type: String, required: true, unique: true },
  agentName: { type: String, required: true },
  password: { type: String, required: true, default: '123456' },
  role: { type: String, default: 'agent' },
  funds: { type: Number, default: 10000 },
  lotteryName: { type: String, default: 'LOTATO PRO' },
  lotteryLogo: { type: String, default: '' },
  lotteryAddress: { type: String, default: '' },
  lotteryPhone: { type: String, default: '' },
  isActive: { type: Boolean, default: true },
  supervisorId: { type: String, required: true },
  lastActivity: { type: Date, default: Date.now },
  online: { type: Boolean, default: false },
  location: { type: String, default: '' },
  createdAt: { type: Date, default: Date.now }
});

const supervisorSchema = new mongoose.Schema({
  username: { type: String, required: true, unique: true },
  password: { type: String, required: true, default: '123456' },
  name: { type: String, required: true },
  role: { type: String, default: 'supervisor' },
  permissions: [String],
  maxDeleteTime: { type: Number, default: 10 },
  isActive: { type: Boolean, default: true },
  createdAt: { type: Date, default: Date.now }
});

const ownerSchema = new mongoose.Schema({
  username: { type: String, required: true, unique: true },
  password: { type: String, required: true, default: '123456' },
  name: { type: String, required: true },
  role: { type: String, default: 'owner' },
  isActive: { type: Boolean, default: true },
  createdAt: { type: Date, default: Date.now }
});

// === NOUVEAUX SCHÉMAS POUR PROPRIÉTAIRE ===
const drawConfigSchema = new mongoose.Schema({
  drawId: { type: String, required: true, unique: true },
  drawName: { type: String, required: true },
  drawTime: { type: String, required: true },
  isActive: { type: Boolean, default: true },
  isBlocked: { type: Boolean, default: false },
  lastResult: { type: String, default: '' },
  lastDrawDate: { type: Date, default: null },
  createdAt: { type: Date, default: Date.now }
});

const ballSchema = new mongoose.Schema({
  ballNumber: { type: String, required: true, unique: true },
  isBlocked: { type: Boolean, default: false },
  limitAmount: { type: Number, default: 0 },
  currentAmount: { type: Number, default: 0 },
  blockedAt: { type: Date, default: null },
  blockedBy: { type: String, default: '' }
});

const gameRuleSchema = new mongoose.Schema({
  gameType: { type: String, required: true, unique: true },
  gameName: { type: String, required: true },
  payouts: { type: Map, of: Number },
  isActive: { type: Boolean, default: true },
  updatedAt: { type: Date, default: Date.now }
});

const publishedDrawSchema = new mongoose.Schema({
  drawId: { type: String, required: true },
  drawName: { type: String, required: true },
  results: { type: [String], required: true },
  luckyNumber: { type: String, default: '' },
  publishedAt: { type: Date, default: Date.now },
  publishedBy: { type: String, required: true },
  source: { type: String, default: 'manual' },
  status: { type: String, default: 'published' }
});

const activityLogSchema = new mongoose.Schema({
  userId: { type: String, required: true },
  userRole: { type: String, required: true },
  action: { type: String, required: true },
  details: { type: String, default: '' },
  ipAddress: { type: String, default: '' },
  createdAt: { type: Date, default: Date.now }
});

// === MODÈLES ===
const Ticket = mongoose.model('Ticket', ticketSchema);
const Winner = mongoose.model('Winner', winnerSchema);
const Agent = mongoose.model('Agent', agentSchema);
const Supervisor = mongoose.model('Supervisor', supervisorSchema);
const Owner = mongoose.model('Owner', ownerSchema);
const DrawConfig = mongoose.model('DrawConfig', drawConfigSchema);
const Ball = mongoose.model('Ball', ballSchema);
const GameRule = mongoose.model('GameRule', gameRuleSchema);
const PublishedDraw = mongoose.model('PublishedDraw', publishedDrawSchema);
const ActivityLog = mongoose.model('ActivityLog', activityLogSchema);

// Middleware d'authentification
const authenticate = async (req, res, next) => {
  try {
    const token = req.headers.authorization?.replace('Bearer ', '');
    
    if (!token) {
      return res.status(401).json({
        success: false,
        message: 'Token otantifikasyon obligatwa'
      });
    }

    const decoded = jwt.verify(token, JWT_SECRET);
    req.user = decoded;
    next();
  } catch (error) {
    return res.status(401).json({
      success: false,
      message: 'Token pa valab'
    });
  }
};

// Middleware de vérification de rôle
const requireRole = (roles) => {
  return (req, res, next) => {
    if (!roles.includes(req.user.role)) {
      return res.status(403).json({
        success: false,
        message: 'Ou pa gen otorizasyon pou aksyon sa a'
      });
    }
    next();
  };
};

// === ROUTES D'AUTHENTIFICATION ===

// Connexion Propriétaire (existant)
app.post('/api/auth/owner-login', async (req, res) => {
  try {
    const { username, password } = req.body;
    
    if (mongoose.connection.readyState !== 1) {
      return res.status(503).json({
        success: false,
        message: 'Sistèm nan ap travay, tanpri eseye ankò nan kèk moman'
      });
    }
    
    const owner = await Owner.findOne({ 
      username: username.toLowerCase(),
      isActive: true 
    });
    
    if (!owner) {
      return res.status(401).json({
        success: false,
        message: 'Pwopriyetè pa egziste'
      });
    }

    if (owner.password !== password) {
      return res.status(401).json({
        success: false,
        message: 'Modpas pa kòrèk'
      });
    }

    const token = jwt.sign(
      {
        id: owner._id,
        username: owner.username,
        name: owner.name,
        role: 'owner'
      },
      JWT_SECRET,
      { expiresIn: '24h' }
    );

    res.json({
      success: true,
      message: 'Koneksyon reyisi',
      token: token,
      user: {
        id: owner._id,
        username: owner.username,
        name: owner.name,
        role: 'owner'
      }
    });
  } catch (error) {
    console.error('Erreur connexion propriétaire:', error);
    res.status(500).json({
      success: false,
      message: 'Erè sèvè entèn'
    });
  }
});

// === ROUTES PROPRIÉTAIRE ===

// 1. Dashboard Propriétaire
app.get('/api/owner/dashboard', authenticate, requireRole(['owner']), async (req, res) => {
  try {
    if (mongoose.connection.readyState !== 1) {
      return res.status(503).json({
        success: false,
        message: 'Sistèm nan ap travay, tanpri eseye ankò nan kèk moman'
      });
    }
    
    // Récupérer les statistiques
    const totalAgents = await Agent.countDocuments();
    const totalSupervisors = await Supervisor.countDocuments();
    const onlineAgents = await Agent.countDocuments({ online: true });
    const onlineSupervisors = await Supervisor.countDocuments({ online: true });
    
    // Calculer les ventes d'aujourd'hui
    const today = new Date();
    today.setHours(0, 0, 0, 0);
    
    const todayTickets = await Ticket.find({ date: { $gte: today } });
    const todaySales = todayTickets.reduce((sum, ticket) => sum + ticket.total, 0);
    const todayWinners = await Winner.find({ date: { $gte: today } });
    const todayWins = todayWinners.reduce((sum, winner) => sum + winner.winningAmount, 0);
    
    // Récupérer les tirages actifs
    const activeDraws = await DrawConfig.countDocuments({ isActive: true });
    const totalDraws = await DrawConfig.countDocuments();
    
    // Récupérer les boules bloquées
    const blockedBalls = await Ball.countDocuments({ isBlocked: true });
    
    // Récupérer les activités récentes
    const recentActivities = await ActivityLog.find()
      .sort({ createdAt: -1 })
      .limit(5);
    
    res.json({
      success: true,
      stats: {
        totalAgents,
        totalSupervisors,
        onlineAgents,
        onlineSupervisors,
        todaySales,
        todayWins,
        activeDraws,
        totalDraws,
        blockedBalls
      },
      recentActivities
    });
    
  } catch (error) {
    console.error('Erreur dashboard propriétaire:', error);
    res.status(500).json({
      success: false,
      message: 'Erè charjman dashboard'
    });
  }
});

// 2. Récupérer tous les utilisateurs
app.get('/api/owner/users', authenticate, requireRole(['owner']), async (req, res) => {
  try {
    if (mongoose.connection.readyState !== 1) {
      return res.status(503).json({
        success: false,
        message: 'Sistèm nan ap travay, tanpri eseye ankò nan kèk moman'
      });
    }
    
    const agents = await Agent.find().select('-password');
    const supervisors = await Supervisor.find().select('-password');
    
    // Pour chaque superviseur, compter le nombre d'agents
    const supervisorsWithAgentCount = await Promise.all(supervisors.map(async (supervisor) => {
      const agentCount = await Agent.countDocuments({ supervisorId: supervisor.username });
      return {
        ...supervisor.toObject(),
        agentCount
      };
    }));
    
    res.json({
      success: true,
      agents,
      supervisors: supervisorsWithAgentCount
    });
    
  } catch (error) {
    console.error('Erreur récupération utilisateurs:', error);
    res.status(500).json({
      success: false,
      message: 'Erè récupération itilizatè yo'
    });
  }
});

// 3. Créer un nouvel utilisateur
app.post('/api/owner/users', authenticate, requireRole(['owner']), async (req, res) => {
  try {
    const { type, username, name, password, email, phone, supervisorId, location, commission } = req.body;
    
    if (mongoose.connection.readyState !== 1) {
      return res.status(503).json({
        success: false,
        message: 'Sistèm nan ap travay, tanpri eseye ankò nan kèk moman'
      });
    }
    
    if (type === 'supervisor') {
      // Créer un superviseur
      const existingSupervisor = await Supervisor.findOne({ username });
      if (existingSupervisor) {
        return res.status(400).json({
          success: false,
          message: 'Non itilizatè sa deja egziste'
        });
      }
      
      const supervisor = new Supervisor({
        username,
        password,
        name,
        email,
        phone
      });
      
      await supervisor.save();
      
      // Log d'activité
      await ActivityLog.create({
        userId: req.user.id,
        userRole: 'owner',
        action: 'create_supervisor',
        details: `Superviseur ${name} créé`
      });
      
      res.json({
        success: true,
        message: 'Supervizè kreye avèk siksè',
        user: supervisor
      });
      
    } else if (type === 'agent') {
      // Créer un agent
      const existingAgent = await Agent.findOne({ agentId: username.toUpperCase() });
      if (existingAgent) {
        return res.status(400).json({
          success: false,
          message: 'Kòd ajan sa deja egziste'
        });
      }
      
      // Vérifier que le superviseur existe
      const supervisor = await Supervisor.findOne({ username: supervisorId });
      if (!supervisor) {
        return res.status(400).json({
          success: false,
          message: 'Supervizè pa egziste'
        });
      }
      
      const agent = new Agent({
        agentId: username.toUpperCase(),
        agentName: name,
        password,
        email,
        phone,
        supervisorId: supervisorId,
        location,
        commission: commission || 5
      });
      
      await agent.save();
      
      // Log d'activité
      await ActivityLog.create({
        userId: req.user.id,
        userRole: 'owner',
        action: 'create_agent',
        details: `Agent ${name} créé pour superviseur ${supervisorId}`
      });
      
      res.json({
        success: true,
        message: 'Ajan kreye avèk siksè',
        user: agent
      });
    } else {
      return res.status(400).json({
        success: false,
        message: 'Tip itilizatè pa valab'
      });
    }
    
  } catch (error) {
    console.error('Erreur création utilisateur:', error);
    res.status(500).json({
      success: false,
      message: 'Erè kreye itilizatè'
    });
  }
});

// 4. Bloquer/débloquer un utilisateur
app.post('/api/owner/users/:userId/block', authenticate, requireRole(['owner']), async (req, res) => {
  try {
    const { userId } = req.params;
    const { block } = req.body;
    
    if (mongoose.connection.readyState !== 1) {
      return res.status(503).json({
        success: false,
        message: 'Sistèm nan ap travay, tanpri eseye ankò nan kèk moman'
      });
    }
    
    // Chercher dans les agents
    let user = await Agent.findOne({ agentId: userId });
    let userType = 'agent';
    
    if (!user) {
      // Chercher dans les superviseurs
      user = await Supervisor.findOne({ username: userId });
      userType = 'supervisor';
    }
    
    if (!user) {
      return res.status(404).json({
        success: false,
        message: 'Itilizatè pa jwenn'
      });
    }
    
    user.isActive = !block;
    await user.save();
    
    // Si c'est un superviseur et qu'on le bloque, bloquer aussi ses agents
    if (userType === 'supervisor' && block) {
      await Agent.updateMany(
        { supervisorId: userId },
        { isActive: false }
      );
    }
    
    // Log d'activité
    await ActivityLog.create({
      userId: req.user.id,
      userRole: 'owner',
      action: block ? 'block_user' : 'unblock_user',
      details: `${userType} ${userId} ${block ? 'bloqué' : 'débloqué'}`
    });
    
    res.json({
      success: true,
      message: `Itilizatè ${block ? 'bloke' : 'debloke'} avèk siksè`,
      isActive: user.isActive
    });
    
  } catch (error) {
    console.error('Erreur blocage utilisateur:', error);
    res.status(500).json({
      success: false,
      message: 'Erè bloke/debloke itilizatè'
    });
  }
});

// 5. Transférer un agent
app.post('/api/owner/users/:agentId/transfer', authenticate, requireRole(['owner']), async (req, res) => {
  try {
    const { agentId } = req.params;
    const { newSupervisorId } = req.body;
    
    if (mongoose.connection.readyState !== 1) {
      return res.status(503).json({
        success: false,
        message: 'Sistèm nan ap travay, tanpri eseye ankò nan kèk moman'
      });
    }
    
    const agent = await Agent.findOne({ agentId });
    if (!agent) {
      return res.status(404).json({
        success: false,
        message: 'Ajan pa jwenn'
      });
    }
    
    const newSupervisor = await Supervisor.findOne({ username: newSupervisorId });
    if (!newSupervisor) {
      return res.status(404).json({
        success: false,
        message: 'Nouvo superviseur pa jwenn'
      });
    }
    
    const oldSupervisorId = agent.supervisorId;
    
    agent.supervisorId = newSupervisorId;
    await agent.save();
    
    // Log d'activité
    await ActivityLog.create({
      userId: req.user.id,
      userRole: 'owner',
      action: 'transfer_agent',
      details: `Agent ${agentId} transféré de ${oldSupervisorId} à ${newSupervisorId}`
    });
    
    res.json({
      success: true,
      message: 'Ajan transfere avèk siksè',
      newSupervisor: newSupervisor.name
    });
    
  } catch (error) {
    console.error('Erreur transfert agent:', error);
    res.status(500).json({
      success: false,
      message: 'Erè transfere ajan'
    });
  }
});

// 6. Gestion des tirages
app.get('/api/owner/draws', authenticate, requireRole(['owner']), async (req, res) => {
  try {
    if (mongoose.connection.readyState !== 1) {
      return res.status(503).json({
        success: false,
        message: 'Sistèm nan ap travay, tanpri eseye ankò nan kèk moman'
      });
    }
    
    const draws = await DrawConfig.find().sort({ drawTime: 1 });
    
    // Calculer les ventes pour chaque tirage
    const today = new Date();
    today.setHours(0, 0, 0, 0);
    
    const drawsWithSales = await Promise.all(draws.map(async (draw) => {
      const sales = await Ticket.aggregate([
        {
          $match: {
            drawId: draw.drawId,
            date: { $gte: today }
          }
        },
        {
          $group: {
            _id: null,
            total: { $sum: '$total' }
          }
        }
      ]);
      
      return {
        ...draw.toObject(),
        sales: sales.length > 0 ? sales[0].total : 0
      };
    }));
    
    res.json({
      success: true,
      draws: drawsWithSales
    });
    
  } catch (error) {
    console.error('Erreur récupération tirages:', error);
    res.status(500).json({
      success: false,
      message: 'Erè récupération tirages'
    });
  }
});

// 7. Activer/désactiver un tirage
app.post('/api/owner/draws/:drawId/toggle', authenticate, requireRole(['owner']), async (req, res) => {
  try {
    const { drawId } = req.params;
    const { isActive } = req.body;
    
    if (mongoose.connection.readyState !== 1) {
      return res.status(503).json({
        success: false,
        message: 'Sistèm nan ap travay, tanpri eseye ankò nan kèk moman'
      });
    }
    
    const draw = await DrawConfig.findOne({ drawId });
    if (!draw) {
      return res.status(404).json({
        success: false,
        message: 'Tiraj pa jwenn'
      });
    }
    
    draw.isActive = isActive;
    await draw.save();
    
    // Log d'activité
    await ActivityLog.create({
      userId: req.user.id,
      userRole: 'owner',
      action: isActive ? 'activate_draw' : 'deactivate_draw',
      details: `Tiraj ${draw.drawName} ${isActive ? 'activé' : 'désactivé'}`
    });
    
    res.json({
      success: true,
      message: `Tiraj ${isActive ? 'aktive' : 'dezaktiye'} avèk siksè`,
      isActive: draw.isActive
    });
    
  } catch (error) {
    console.error('Erreur modification tirage:', error);
    res.status(500).json({
      success: false,
      message: 'Erè modifye tiraj'
    });
  }
});

// 8. Gestion des boules
app.get('/api/owner/balls', authenticate, requireRole(['owner']), async (req, res) => {
  try {
    if (mongoose.connection.readyState !== 1) {
      return res.status(503).json({
        success: false,
        message: 'Sistèm nan ap travay, tanpri eseye ankò nan kèk moman'
      });
    }
    
    const balls = await Ball.find().sort({ ballNumber: 1 });
    
    // Si aucune boule n'existe, initialiser
    if (balls.length === 0) {
      const ballArray = [];
      for (let i = 0; i < 100; i++) {
        const num = i.toString().padStart(2, '0');
        ballArray.push({
          ballNumber: num,
          isBlocked: false,
          limitAmount: 0,
          currentAmount: 0
        });
      }
      await Ball.insertMany(ballArray);
      
      const newBalls = await Ball.find().sort({ ballNumber: 1 });
      return res.json({
        success: true,
        balls: newBalls
      });
    }
    
    res.json({
      success: true,
      balls
    });
    
  } catch (error) {
    console.error('Erreur récupération boules:', error);
    res.status(500).json({
      success: false,
      message: 'Erè récupération boul yo'
    });
  }
});

// 9. Bloquer/débloquer une boule
app.post('/api/owner/balls/:ballNumber/block', authenticate, requireRole(['owner']), async (req, res) => {
  try {
    const { ballNumber } = req.params;
    const { isBlocked } = req.body;
    
    if (mongoose.connection.readyState !== 1) {
      return res.status(503).json({
        success: false,
        message: 'Sistèm nan ap travay, tanpri eseye ankò nan kèk moman'
      });
    }
    
    let ball = await Ball.findOne({ ballNumber });
    
    if (!ball) {
      ball = new Ball({
        ballNumber,
        isBlocked,
        blockedAt: isBlocked ? new Date() : null,
        blockedBy: req.user.username
      });
    } else {
      ball.isBlocked = isBlocked;
      ball.blockedAt = isBlocked ? new Date() : null;
      ball.blockedBy = isBlocked ? req.user.username : '';
    }
    
    await ball.save();
    
    // Log d'activité
    await ActivityLog.create({
      userId: req.user.id,
      userRole: 'owner',
      action: isBlocked ? 'block_ball' : 'unblock_ball',
      details: `Boule ${ballNumber} ${isBlocked ? 'bloquée' : 'débloquée'}`
    });
    
    res.json({
      success: true,
      message: `Boule ${ballNumber} ${isBlocked ? 'bloke' : 'debloke'} avèk siksè`,
      ball
    });
    
  } catch (error) {
    console.error('Erreur blocage boule:', error);
    res.status(500).json({
      success: false,
      message: 'Erè bloke/debloke boule'
    });
  }
});

// 10. Définir une limite pour une boule
app.post('/api/owner/balls/:ballNumber/limit', authenticate, requireRole(['owner']), async (req, res) => {
  try {
    const { ballNumber } = req.params;
    const { limitAmount } = req.body;
    
    if (mongoose.connection.readyState !== 1) {
      return res.status(503).json({
        success: false,
        message: 'Sistèm nan ap travay, tanpri eseye ankò nan kèk moman'
      });
    }
    
    let ball = await Ball.findOne({ ballNumber });
    
    if (!ball) {
      ball = new Ball({
        ballNumber,
        limitAmount,
        currentAmount: 0
      });
    } else {
      ball.limitAmount = limitAmount;
    }
    
    await ball.save();
    
    // Log d'activité
    await ActivityLog.create({
      userId: req.user.id,
      userRole: 'owner',
      action: 'set_ball_limit',
      details: `Limite définie pour boule ${ballNumber}: ${limitAmount} Gdes`
    });
    
    res.json({
      success: true,
      message: `Limit pou boule ${ballNumber} defini avèk siksè`,
      ball
    });
    
  } catch (error) {
    console.error('Erreur définition limite:', error);
    res.status(500).json({
      success: false,
      message: 'Erè defini limit boule'
    });
  }
});

// 11. Règles de jeu
app.get('/api/owner/rules', authenticate, requireRole(['owner']), async (req, res) => {
  try {
    if (mongoose.connection.readyState !== 1) {
      return res.status(503).json({
        success: false,
        message: 'Sistèm nan ap travay, tanpri eseye ankò nan kèk moman'
      });
    }
    
    const rules = await GameRule.find();
    
    // Si aucune règle n'existe, initialiser
    if (rules.length === 0) {
      const defaultRules = [
        {
          gameType: 'borlette',
          gameName: 'Borlette',
          payouts: { lot1: 60, lot2: 20, lot3: 10 },
          isActive: true
        },
        {
          gameType: 'lotto3',
          gameName: 'Lotto 3',
          payouts: { win: 500 },
          isActive: true
        },
        {
          gameType: 'lotto4',
          gameName: 'Lotto 4',
          payouts: { win: 1000 },
          isActive: true
        },
        {
          gameType: 'lotto5',
          gameName: 'Lotto 5',
          payouts: { win: 5000 },
          isActive: true
        },
        {
          gameType: 'mariage',
          gameName: 'Mariage',
          payouts: { win: 1000 },
          isActive: true
        }
      ];
      
      await GameRule.insertMany(defaultRules);
      const newRules = await GameRule.find();
      return res.json({
        success: true,
        rules: newRules
      });
    }
    
    res.json({
      success: true,
      rules
    });
    
  } catch (error) {
    console.error('Erreur récupération règles:', error);
    res.status(500).json({
      success: false,
      message: 'Erè récupération règlement yo'
    });
  }
});

// 12. Modifier une règle
app.put('/api/owner/rules/:gameType', authenticate, requireRole(['owner']), async (req, res) => {
  try {
    const { gameType } = req.params;
    const { payouts, isActive } = req.body;
    
    if (mongoose.connection.readyState !== 1) {
      return res.status(503).json({
        success: false,
        message: 'Sistèm nan ap travay, tanpri eseye ankò nan kèk moman'
      });
    }
    
    const rule = await GameRule.findOneAndUpdate(
      { gameType },
      { payouts, isActive, updatedAt: new Date() },
      { new: true, upsert: true }
    );
    
    // Log d'activité
    await ActivityLog.create({
      userId: req.user.id,
      userRole: 'owner',
      action: 'update_rule',
      details: `Règle ${gameType} mise à jour`
    });
    
    res.json({
      success: true,
      message: 'Règlement mete ajou avèk siksè',
      rule
    });
    
  } catch (error) {
    console.error('Erreur modification règle:', error);
    res.status(500).json({
      success: false,
      message: 'Erè mete ajou règlement'
    });
  }
});

// 13. Publication de tirage
app.post('/api/owner/draws/publish', authenticate, requireRole(['owner']), async (req, res) => {
  try {
    const { drawName, results, luckyNumber, publishedBy, source } = req.body;
    
    if (mongoose.connection.readyState !== 1) {
      return res.status(503).json({
        success: false,
        message: 'Sistèm nan ap travay, tanpri eseye ankò nan kèk moman'
      });
    }
    
    if (!results || !Array.isArray(results) || results.length < 5) {
      return res.status(400).json({
        success: false,
        message: '5 rezilta obligatwa'
      });
    }
    
    const drawId = `DRAW-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
    
    const publishedDraw = new PublishedDraw({
      drawId,
      drawName,
      results: results.map(r => r.toString().padStart(2, '0')),
      luckyNumber: luckyNumber ? luckyNumber.toString().padStart(2, '0') : '',
      publishedBy,
      source: source || 'manual'
    });
    
    await publishedDraw.save();
    
    // Mettre à jour le tirage correspondant
    const drawConfig = await DrawConfig.findOne({ drawName });
    if (drawConfig) {
      drawConfig.lastResult = results.join(',');
      drawConfig.lastDrawDate = new Date();
      await drawConfig.save();
    }
    
    // Log d'activité
    await ActivityLog.create({
      userId: req.user.id,
      userRole: 'owner',
      action: 'publish_draw',
      details: `Tirage ${drawName} publié: ${results.join(',')}`
    });
    
    res.json({
      success: true,
      message: 'Tiraj pibliye avèk siksè',
      draw: publishedDraw
    });
    
  } catch (error) {
    console.error('Erreur publication tirage:', error);
    res.status(500).json({
      success: false,
      message: 'Erè pibliye tiraj'
    });
  }
});

// 14. Historique des publications
app.get('/api/owner/draws/history', authenticate, requireRole(['owner']), async (req, res) => {
  try {
    const { limit = 20 } = req.query;
    
    if (mongoose.connection.readyState !== 1) {
      return res.status(503).json({
        success: false,
        message: 'Sistèm nan ap travay, tanpri eseye ankò nan kèk moman'
      });
    }
    
    const history = await PublishedDraw.find()
      .sort({ publishedAt: -1 })
      .limit(parseInt(limit));
    
    res.json({
      success: true,
      history
    });
    
  } catch (error) {
    console.error('Erreur récupération historique:', error);
    res.status(500).json({
      success: false,
      message: 'Erè récupération istorik'
    });
  }
});

// 15. Journal d'activité
app.get('/api/owner/activity', authenticate, requireRole(['owner']), async (req, res) => {
  try {
    const { limit = 50 } = req.query;
    
    if (mongoose.connection.readyState !== 1) {
      return res.status(503).json({
        success: false,
        message: 'Sistèm nan ap travay, tanpri eseye ankò nan kèk moman'
      });
    }
    
    const activities = await ActivityLog.find()
      .sort({ createdAt: -1 })
      .limit(parseInt(limit));
    
    res.json({
      success: true,
      activities
    });
    
  } catch (error) {
    console.error('Erreur récupération journal:', error);
    res.status(500).json({
      success: false,
      message: 'Erè récupération jounal aktivite'
    });
  }
});

// 16. Initialisation des données par défaut
app.post('/api/owner/init-defaults', authenticate, requireRole(['owner']), async (req, res) => {
  try {
    if (mongoose.connection.readyState !== 1) {
      return res.status(503).json({
        success: false,
        message: 'Sistèm nan ap travay, tanpri eseye ankò nan kèk moman'
      });
    }
    
    // Tirages par défaut
    const defaultDraws = [
      { drawId: 'flo_matin', drawName: 'Florida Matin', drawTime: '13:30', isActive: true },
      { drawId: 'flo_soir', drawName: 'Florida Soir', drawTime: '21:50', isActive: true },
      { drawId: 'ny_matin', drawName: 'New York Matin', drawTime: '14:30', isActive: true },
      { drawId: 'ny_soir', drawName: 'New York Soir', drawTime: '20:00', isActive: true },
      { drawId: 'ga_matin', drawName: 'Georgia Matin', drawTime: '12:30', isActive: false },
      { drawId: 'ga_soir', drawName: 'Georgia Soir', drawTime: '19:00', isActive: true },
      { drawId: 'tx_matin', drawName: 'Texas Matin', drawTime: '11:30', isActive: true },
      { drawId: 'tx_soir', drawName: 'Texas Soir', drawTime: '18:30', isActive: true },
      { drawId: 'tn_matin', drawName: 'Tunisia Matin', drawTime: '10:00', isActive: true },
      { drawId: 'tn_soir', drawName: 'Tunisia Soir', drawTime: '17:00', isActive: false }
    ];
    
    // Boules par défaut (0-99)
    const defaultBalls = Array.from({ length: 100 }, (_, i) => ({
      ballNumber: i.toString().padStart(2, '0'),
      isBlocked: false,
      limitAmount: 0,
      currentAmount: 0
    }));
    
    // Règles par défaut
    const defaultRules = [
      { gameType: 'borlette', gameName: 'Borlette', payouts: { lot1: 60, lot2: 20, lot3: 10 }, isActive: true },
      { gameType: 'lotto3', gameName: 'Lotto 3', payouts: { win: 500 }, isActive: true },
      { gameType: 'lotto4', gameName: 'Lotto 4', payouts: { win: 1000 }, isActive: true },
      { gameType: 'lotto5', gameName: 'Lotto 5', payouts: { win: 5000 }, isActive: true },
      { gameType: 'mariage', gameName: 'Mariage', payouts: { win: 1000 }, isActive: true }
    ];
    
    // Vérifier et créer les tirages
    for (const draw of defaultDraws) {
      const existing = await DrawConfig.findOne({ drawId: draw.drawId });
      if (!existing) {
        await DrawConfig.create(draw);
      }
    }
    
    // Vérifier et créer les boules
    const ballCount = await Ball.countDocuments();
    if (ballCount === 0) {
      await Ball.insertMany(defaultBalls);
    }
    
    // Vérifier et créer les règles
    const ruleCount = await GameRule.countDocuments();
    if (ruleCount === 0) {
      await GameRule.insertMany(defaultRules);
    }
    
    res.json({
      success: true,
      message: 'Done default inisyalize avèk siksè'
    });
    
  } catch (error) {
    console.error('Erreur initialisation:', error);
    res.status(500).json({
      success: false,
      message: 'Erè inisyalizasyon'
    });
  }
});

// === ROUTES SUPERVISEUR (existant) ===
// ... (garder toutes les routes superviseur existantes)

// === ROUTES AGENT (existant) ===
// ... (garder toutes les routes agent existantes)

// Route de vérification
app.get('/api/health', (req, res) => {
  res.json({
    success: true,
    message: 'API LOTATO PRO fonctionne',
    timestamp: new Date().toISOString(),
    version: '3.0.0',
    mongodbStatus: mongoose.connection.readyState === 1 ? 'connected' : 'disconnected',
    nodeEnv: process.env.NODE_ENV || 'development'
  });
});

// Route de test
app.get('/', (req, res) => {
  res.sendFile(__dirname + '/index.html');
});

// Routes pour les pages protégées
app.get('/agent1.html', authenticate, (req, res) => {
  if (req.user.role === 'agent') {
    res.sendFile(__dirname + '/agent1.html');
  } else {
    res.status(403).send('Accès non autorisé');
  }
});

app.get('/supervisor.html', authenticate, (req, res) => {
  if (req.user.role === 'supervisor') {
    res.sendFile(__dirname + '/supervisor.html');
  } else {
    res.status(403).send('Accès non autorisé');
  }
});

app.get('/owner.html', authenticate, (req, res) => {
  if (req.user.role === 'owner') {
    res.sendFile(__dirname + '/owner.html');
  } else {
    res.status(403).send('Accès non autorisé');
  }
});

// Redirection pour responsable.html
app.get('/responsable.html', authenticate, (req, res) => {
  if (req.user.role === 'supervisor') {
    res.sendFile(__dirname + '/supervisor.html');
  } else {
    res.status(403).send('Accès non autorisé');
  }
});

// Gestion des erreurs 404
app.use((req, res) => {
  res.status(404).json({
    success: false,
    message: 'Rout pa jwenn'
  });
});

// Middleware de gestion d'erreurs global
app.use((err, req, res, next) => {
  console.error('Erreur globale:', err);
  res.status(500).json({
    success: false,
    message: 'Erè sèvè entèn'
  });
});

// Démarrer le serveur
app.listen(PORT, () => {
  console.log(`🚀 Serveur démarré sur le port ${PORT}`);
  console.log(`📡 API disponible à http://localhost:${PORT}`);
  console.log(`🔐 Page de connexion: http://localhost:${PORT}/`);
  console.log(`🌐 Environnement: ${process.env.NODE_ENV || 'development'}`);
  
  // Vérifier la connexion MongoDB
  setTimeout(() => {
    if (mongoose.connection.readyState === 1) {
      console.log('✅ MongoDB: Connecté');
    } else {
      console.log('⚠️ MongoDB: En attente de connexion...');
    }
  }, 1000);
});