const express = require('express');
const mongoose = require('mongoose');
const cors = require('cors');
const jwt = require('jsonwebtoken');
require('dotenv').config();

const app = express();
const PORT = process.env.PORT || 3000;

// Middleware
app.use(cors());
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(express.static('.'));

// JWT Secret
const JWT_SECRET = process.env.JWT_SECRET || 'lotato-pro-super-secret-key-2024';

// Connexion MongoDB Atlas
const MONGODB_URI = process.env.MONGODB_URI || 'mongodb://localhost:27017/lotato';

mongoose.connect(MONGODB_URI, {
  useNewUrlParser: true,
  useUnifiedTopology: true,
  serverSelectionTimeoutMS: 5000, // Timeout après 5 secondes
  socketTimeoutMS: 45000, // Close sockets après 45s d'inactivité
})
.then(() => console.log('✅ Connecté à MongoDB Atlas'))
.catch(err => {
  console.error('❌ Erreur MongoDB:', err.message);
  console.log('🔗 URI utilisée:', MONGODB_URI.replace(/mongodb\+srv:\/\/([^:]+):([^@]+)@/, 'mongodb+srv://USERNAME:PASSWORD@'));
});

// Schémas et Modèles (gardez les mêmes que précédemment)
const ticketSchema = new mongoose.Schema({
  ticketId: { type: String, required: true, unique: true },
  agentId: { type: String, required: true },
  agentName: { type: String, required: true },
  drawId: { type: String, required: true },
  drawName: { type: String, required: true },
  bets: [{
    game: String,
    number: String,
    cleanNumber: String,
    amount: Number,
    isAutoGenerated: Boolean,
    specialType: String,
    gain: { type: Number, default: 0 }
  }],
  total: { type: Number, required: true },
  checked: { type: Boolean, default: false },
  date: { type: Date, default: Date.now }
});

const winnerSchema = new mongoose.Schema({
  ticketId: { type: String, required: true },
  agentId: { type: String, required: true },
  drawId: { type: String, required: true },
  drawName: { type: String, required: true },
  gameType: { type: String, required: true },
  winningNumber: { type: String, required: true },
  winningAmount: { type: Number, required: true },
  customerName: { type: String, default: '' },
  paid: { type: Boolean, default: false },
  date: { type: Date, default: Date.now }
});

const agentSchema = new mongoose.Schema({
  agentId: { type: String, required: true, unique: true },
  agentName: { type: String, required: true },
  password: { type: String, required: true, default: '123456' },
  role: { type: String, default: 'agent' },
  funds: { type: Number, default: 10000 },
  lotteryName: { type: String, default: 'LOTATO PRO' },
  lotteryLogo: { type: String, default: '' },
  lotteryAddress: { type: String, default: '' },
  lotteryPhone: { type: String, default: '' },
  isActive: { type: Boolean, default: true },
  createdAt: { type: Date, default: Date.now }
});

const supervisorSchema = new mongoose.Schema({
  username: { type: String, required: true, unique: true },
  password: { type: String, required: true, default: '123456' },
  name: { type: String, required: true },
  role: { type: String, default: 'supervisor' },
  permissions: [String],
  isActive: { type: Boolean, default: true },
  createdAt: { type: Date, default: Date.now }
});

const ownerSchema = new mongoose.Schema({
  username: { type: String, required: true, unique: true },
  password: { type: String, required: true, default: '123456' },
  name: { type: String, required: true },
  role: { type: String, default: 'owner' },
  isActive: { type: Boolean, default: true },
  createdAt: { type: Date, default: Date.now }
});

const Ticket = mongoose.model('Ticket', ticketSchema);
const Winner = mongoose.model('Winner', winnerSchema);
const Agent = mongoose.model('Agent', agentSchema);
const Supervisor = mongoose.model('Supervisor', supervisorSchema);
const Owner = mongoose.model('Owner', ownerSchema);

// Middleware d'authentification
const authenticate = async (req, res, next) => {
  try {
    const token = req.headers.authorization?.replace('Bearer ', '');
    
    if (!token) {
      return res.status(401).json({
        success: false,
        message: 'Token otantifikasyon obligatwa'
      });
    }

    const decoded = jwt.verify(token, JWT_SECRET);
    req.user = decoded;
    next();
  } catch (error) {
    return res.status(401).json({
      success: false,
      message: 'Token pa valab'
    });
  }
};

// Middleware de vérification de rôle
const requireRole = (roles) => {
  return (req, res, next) => {
    if (!roles.includes(req.user.role)) {
      return res.status(403).json({
        success: false,
        message: 'Ou pa gen otorizasyon pou aksyon sa a'
      });
    }
    next();
  };
};

// === ROUTES D'AUTHENTIFICATION ===

// 1. Connexion Agent
app.post('/api/auth/login', async (req, res) => {
  try {
    const { username, password } = req.body;
    
    const agent = await Agent.findOne({ 
      agentId: username.toUpperCase(),
      isActive: true 
    });
    
    if (!agent) {
      return res.status(401).json({
        success: false,
        message: 'Kòd ajan pa egziste'
      });
    }

    if (agent.password !== password) {
      return res.status(401).json({
        success: false,
        message: 'Modpas pa kòrèk'
      });
    }

    const token = jwt.sign(
      {
        id: agent._id,
        agentId: agent.agentId,
        name: agent.agentName,
        role: 'agent'
      },
      JWT_SECRET,
      { expiresIn: '24h' }
    );

    res.json({
      success: true,
      message: 'Koneksyon reyisi',
      token: token,
      user: {
        id: agent._id,
        agentId: agent.agentId,
        name: agent.agentName,
        role: 'agent'
      }
    });
  } catch (error) {
    console.error('Erreur connexion agent:', error);
    res.status(500).json({
      success: false,
      message: 'Erè sèvè entèn'
    });
  }
});

// 2. Connexion Superviseur
app.post('/api/auth/supervisor-login', async (req, res) => {
  try {
    const { username, password } = req.body;
    
    const supervisor = await Supervisor.findOne({ 
      username: username.toLowerCase(),
      isActive: true 
    });
    
    if (!supervisor) {
      return res.status(401).json({
        success: false,
        message: 'Supervizè pa egziste'
      });
    }

    if (supervisor.password !== password) {
      return res.status(401).json({
        success: false,
        message: 'Modpas pa kòrèk'
      });
    }

    const token = jwt.sign(
      {
        id: supervisor._id,
        username: supervisor.username,
        name: supervisor.name,
        role: 'supervisor',
        permissions: supervisor.permissions
      },
      JWT_SECRET,
      { expiresIn: '24h' }
    );

    res.json({
      success: true,
      message: 'Koneksyon reyisi',
      token: token,
      user: {
        id: supervisor._id,
        username: supervisor.username,
        name: supervisor.name,
        role: 'supervisor',
        permissions: supervisor.permissions
      }
    });
  } catch (error) {
    console.error('Erreur connexion superviseur:', error);
    res.status(500).json({
      success: false,
      message: 'Erè sèvè entèn'
    });
  }
});

// 3. Connexion Propriétaire
app.post('/api/auth/owner-login', async (req, res) => {
  try {
    const { username, password } = req.body;
    
    const owner = await Owner.findOne({ 
      username: username.toLowerCase(),
      isActive: true 
    });
    
    if (!owner) {
      return res.status(401).json({
        success: false,
        message: 'Pwopriyetè pa egziste'
      });
    }

    if (owner.password !== password) {
      return res.status(401).json({
        success: false,
        message: 'Modpas pa kòrèk'
      });
    }

    const token = jwt.sign(
      {
        id: owner._id,
        username: owner.username,
        name: owner.name,
        role: 'owner'
      },
      JWT_SECRET,
      { expiresIn: '24h' }
    );

    res.json({
      success: true,
      message: 'Koneksyon reyisi',
      token: token,
      user: {
        id: owner._id,
        username: owner.username,
        name: owner.name,
        role: 'owner'
      }
    });
  } catch (error) {
    console.error('Erreur connexion propriétaire:', error);
    res.status(500).json({
      success: false,
      message: 'Erè sèvè entèn'
    });
  }
});

// 4. Initialiser les comptes par défaut
app.post('/api/init/default-accounts', async (req, res) => {
  try {
    // Créer un agent par défaut
    const existingAgent = await Agent.findOne({ agentId: 'AGENT01' });
    if (!existingAgent) {
      const agent = new Agent({
        agentId: 'AGENT01',
        agentName: 'Ajan Prensipal',
        password: '123456',
        role: 'agent',
        funds: 50000
      });
      await agent.save();
      console.log('✅ Agent par défaut créé');
    }

    // Créer un superviseur par défaut
    const existingSupervisor = await Supervisor.findOne({ username: 'supervisor' });
    if (!existingSupervisor) {
      const supervisor = new Supervisor({
        username: 'supervisor',
        password: '123456',
        name: 'Supervizè Prensipal',
        role: 'supervisor',
        permissions: ['view_all', 'manage_agents', 'approve_funds', 'view_reports']
      });
      await supervisor.save();
      console.log('✅ Superviseur par défaut créé');
    }

    // Créer un propriétaire par défaut
    const existingOwner = await Owner.findOne({ username: 'owner' });
    if (!existingOwner) {
      const owner = new Owner({
        username: 'owner',
        password: '123456',
        name: 'Pwopriyetè',
        role: 'owner'
      });
      await owner.save();
      console.log('✅ Propriétaire par défaut créé');
    }

    res.json({
      success: true,
      message: 'Kont default kreye avèk siksè'
    });
  } catch (error) {
    console.error('Erreur initialisation:', error);
    res.status(500).json({
      success: false,
      message: 'Erè initializasyon'
    });
  }
});

// 5. Test de connexion MongoDB
app.get('/api/test-mongodb', async (req, res) => {
  try {
    // Tester la connexion
    const dbState = mongoose.connection.readyState;
    const states = ['disconnected', 'connected', 'connecting', 'disconnecting'];
    
    // Compter les documents
    const agentCount = await Agent.countDocuments();
    const ticketCount = await Ticket.countDocuments();
    const winnerCount = await Winner.countDocuments();
    
    res.json({
      success: true,
      mongodb: {
        state: states[dbState],
        readyState: dbState,
        database: mongoose.connection.db?.databaseName || 'N/A',
        collections: {
          agents: agentCount,
          tickets: ticketCount,
          winners: winnerCount
        }
      }
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      error: error.message,
      mongodb: {
        state: 'error',
        readyState: mongoose.connection.readyState
      }
    });
  }
});

// === ROUTES PRINCIPALES ===

// Sauvegarder un ticket
app.post('/api/tickets/save', authenticate, requireRole(['agent']), async (req, res) => {
  try {
    const ticketData = req.body;
    const ticketId = `T${Date.now()}${Math.floor(Math.random() * 1000)}`;
    
    const ticket = new Ticket({
      ...ticketData,
      ticketId: ticketId,
      date: new Date()
    });
    
    await ticket.save();
    
    // Mettre à jour les fonds de l'agent
    await Agent.findOneAndUpdate(
      { agentId: ticketData.agentId },
      { $inc: { funds: -ticketData.total } }
    );
    
    res.status(201).json({
      success: true,
      message: 'Ticket sauvegardé avec succès',
      ticket: ticket
    });
  } catch (error) {
    console.error('Erreur sauvegarde ticket:', error);
    res.status(500).json({
      success: false,
      message: 'Erreur lors de la sauvegarde du ticket'
    });
  }
});

// Récupérer les tickets d'un agent
app.get('/api/tickets', authenticate, async (req, res) => {
  try {
    const { agentId } = req.query;
    
    if (req.user.role === 'agent' && req.user.agentId !== agentId) {
      return res.status(403).json({
        success: false,
        message: 'Ou pa gen aksè a istorik ajan sa a'
      });
    }
    
    const tickets = await Ticket.find({ agentId: agentId })
      .sort({ date: -1 })
      .limit(100);
    
    res.json({
      success: true,
      tickets: tickets
    });
  } catch (error) {
    console.error('Erreur récupération tickets:', error);
    res.status(500).json({
      success: false,
      message: 'Erreur lors de la récupération des tickets'
    });
  }
});

// Récupérer les rapports
app.get('/api/reports', authenticate, async (req, res) => {
  try {
    const { agentId } = req.query;
    
    if (req.user.role === 'agent' && req.user.agentId !== agentId) {
      return res.status(403).json({
        success: false,
        message: 'Ou pa gen aksè a rapò ajan sa a'
      });
    }
    
    const tickets = await Ticket.find({ agentId: agentId });
    const totalTickets = tickets.length;
    const totalBets = tickets.reduce((sum, ticket) => sum + ticket.total, 0);
    
    const winners = await Winner.find({ agentId: agentId });
    const totalWins = winners.reduce((sum, winner) => sum + (winner.winningAmount || 0), 0);
    
    const totalLoss = totalBets - totalWins;
    const balance = totalWins - totalLoss;
    
    const gameBreakdown = {};
    tickets.forEach(ticket => {
      ticket.bets.forEach(bet => {
        const game = bet.game;
        if (!gameBreakdown[game]) {
          gameBreakdown[game] = { count: 0, amount: 0 };
        }
        gameBreakdown[game].count += 1;
        gameBreakdown[game].amount += bet.amount;
      });
    });
    
    res.json({
      success: true,
      totalTickets: totalTickets,
      totalBets: totalBets,
      totalWins: totalWins,
      totalLoss: totalLoss,
      balance: balance,
      breakdown: gameBreakdown
    });
  } catch (error) {
    console.error('Erreur récupération rapports:', error);
    res.status(500).json({
      success: false,
      message: 'Erreur lors de la récupération des rapports'
    });
  }
});

// Sauvegarder les gagnants
app.post('/api/winners/save', authenticate, requireRole(['agent']), async (req, res) => {
  try {
    const winnerData = req.body;
    
    const existingWinner = await Winner.findOne({
      ticketId: winnerData.ticketId,
      drawId: winnerData.drawId
    });
    
    let winner;
    if (existingWinner) {
      winner = await Winner.findOneAndUpdate(
        { _id: existingWinner._id },
        winnerData,
        { new: true }
      );
    } else {
      winner = new Winner(winnerData);
      await winner.save();
    }
    
    res.json({
      success: true,
      message: 'Gagnant sauvegardé avec succès',
      winner: winner
    });
  } catch (error) {
    console.error('Erreur sauvegarde gagnant:', error);
    res.status(500).json({
      success: false,
      message: 'Erreur lors de la sauvegarde du gagnant'
    });
  }
});

// Récupérer les gagnants
app.get('/api/winners', authenticate, async (req, res) => {
  try {
    const { agentId } = req.query;
    
    if (req.user.role === 'agent' && req.user.agentId !== agentId) {
      return res.status(403).json({
        success: false,
        message: 'Ou pa gen aksè a ganyen ajan sa a'
      });
    }
    
    const winners = await Winner.find({ agentId: agentId })
      .sort({ date: -1 })
      .limit(50);
    
    res.json({
      success: true,
      winners: winners
    });
  } catch (error) {
    console.error('Erreur récupération gagnants:', error);
    res.status(500).json({
      success: false,
      message: 'Erreur lors de la récupération des gagnants'
    });
  }
});

// Mettre à jour les fonds
app.post('/api/agent/funds', authenticate, requireRole(['agent']), async (req, res) => {
  try {
    const { agentId, amount, type } = req.body;
    
    if (req.user.role === 'agent' && req.user.agentId !== agentId) {
      return res.status(403).json({
        success: false,
        message: 'Ou pa ka modifye fonds ajan sa a'
      });
    }
    
    const agent = await Agent.findOne({ agentId: agentId });
    if (!agent) {
      return res.status(404).json({
        success: false,
        message: 'Agent non trouvé'
      });
    }
    
    let newBalance;
    if (type === 'add') {
      newBalance = agent.funds + amount;
    } else if (type === 'subtract') {
      newBalance = agent.funds - amount;
    } else {
      return res.status(400).json({
        success: false,
        message: 'Type d\'opération invalide'
      });
    }
    
    agent.funds = newBalance;
    await agent.save();
    
    res.json({
      success: true,
      message: 'Fonds mis à jour avec succès',
      newBalance: newBalance
    });
  } catch (error) {
    console.error('Erreur mise à jour fonds:', error);
    res.status(500).json({
      success: false,
      message: 'Erreur lors de la mise à jour des fonds'
    });
  }
});

// Vérifier le statut des tirages
app.get('/api/draws/status', async (req, res) => {
  try {
    const draws = [
      { id: 'mia_matin', name: 'Miami Matin', time: '13:30', blocked: false },
      { id: 'mia_soir', name: 'Miami Soir', time: '21:50', blocked: false },
      { id: 'ny_matin', name: 'New York Matin', time: '14:30', blocked: false },
      { id: 'ny_soir', name: 'New York Soir', time: '20:00', blocked: false },
      { id: 'ga_matin', name: 'Georgia Matin', time: '12:30', blocked: false },
      { id: 'ga_soir', name: 'Georgia Soir', time: '19:00', blocked: false },
      { id: 'tx_matin', name: 'Texas Matin', time: '11:30', blocked: false },
      { id: 'tx_soir', name: 'Texas Soir', time: '18:30', blocked: false },
      { id: 'tn_matin', name: 'Tunisia Matin', time: '10:00', blocked: false },
      { id: 'tn_soir', name: 'Tunisia Soir', time: '17:00', blocked: false }
    ];
    
    const now = new Date();
    draws.forEach(draw => {
      const [hours, minutes] = draw.time.split(':').map(Number);
      const drawTime = new Date();
      drawTime.setHours(hours, minutes, 0, 0);
      
      const blockedTime = new Date(drawTime.getTime() - (3 * 60 * 1000));
      draw.blocked = now >= blockedTime && now < drawTime;
    });
    
    res.json({
      success: true,
      draws: draws,
      serverTime: now.toISOString()
    });
  } catch (error) {
    console.error('Erreur statut tirages:', error);
    res.status(500).json({
      success: false,
      message: 'Erreur lors de la vérification du statut des tirages'
    });
  }
});

// Route santé
app.get('/api/health', async (req, res) => {
  try {
    const dbState = mongoose.connection.readyState;
    const isConnected = dbState === 1;
    
    res.json({
      success: true,
      message: 'API LOTATO PRO fonctionne',
      mongodb: {
        connected: isConnected,
        state: ['disconnected', 'connected', 'connecting', 'disconnecting'][dbState]
      },
      timestamp: new Date().toISOString(),
      version: '2.0.0'
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: 'Problème de connexion',
      error: error.message
    });
  }
});

// Route de test
app.get('/', (req, res) => {
  res.sendFile(__dirname + '/index.html');
});

// Routes pour les pages
app.get('/agent1.html', (req, res) => {
  res.sendFile(__dirname + '/agent1.html');
});

app.get('/supervisor.html', (req, res) => {
  res.sendFile(__dirname + '/supervisor.html');
});

app.get('/owner.html', (req, res) => {
  res.sendFile(__dirname + '/owner.html');
});

// Initialiser les comptes au démarrage
async function initializeDefaultAccounts() {
  try {
    // Vérifier si la base est déjà initialisée
    const agentCount = await Agent.countDocuments();
    
    if (agentCount === 0) {
      console.log('🔄 Initialisation des comptes par défaut...');
      
      // Créer les comptes par défaut
      const agent = new Agent({
        agentId: 'AGENT01',
        agentName: 'Ajan Prensipal',
        password: '123456',
        role: 'agent',
        funds: 50000
      });
      await agent.save();
      
      const supervisor = new Supervisor({
        username: 'supervisor',
        password: '123456',
        name: 'Supervizè Prensipal',
        role: 'supervisor',
        permissions: ['view_all', 'manage_agents', 'approve_funds', 'view_reports']
      });
      await supervisor.save();
      
      const owner = new Owner({
        username: 'owner',
        password: '123456',
        name: 'Pwopriyetè',
        role: 'owner'
      });
      await owner.save();
      
      console.log('✅ Comptes par défaut créés');
    }
  } catch (error) {
    console.error('❌ Erreur initialisation comptes:', error.message);
  }
}

// Gestion des erreurs 404
app.use((req, res) => {
  res.status(404).json({
    success: false,
    message: 'Rout pa jwenn'
  });
});

// Démarrer le serveur
app.listen(PORT, async () => {
  console.log(`🚀 Serveur démarré sur le port ${PORT}`);
  console.log(`📡 API disponible à http://localhost:${PORT}`);
  console.log(`🔐 Page de connexion: http://localhost:${PORT}/`);
  console.log(`🗄️  MongoDB URI: ${MONGODB_URI ? 'Configurée' : 'Non configurée'}`);
  
  // Initialiser les comptes après connexion MongoDB réussie
  mongoose.connection.once('open', async () => {
    console.log('✅ Connexion MongoDB établie');
    await initializeDefaultAccounts();
    
    console.log(`👤 Comptes par défaut:`);
    console.log(`   - Agent: AGENT01 / 123456`);
    console.log(`   - Superviseur: supervisor / 123456`);
    console.log(`   - Propriétaire: owner / 123456`);
  });
});